{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import numpy as np # linear algebra\n",
    "import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import train_test_split\n",
    "import re\n",
    "import gc\n",
    "from sklearn import preprocessing\n",
    "import matplotlib as mpl\n",
    "from functools import wraps\n",
    "import os\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "# from sklearn.externals import joblib\n",
    "from joblib import Parallel, delayed\n",
    "import multiprocessing\n",
    "from datetime import timedelta\n",
    "from io import StringIO\n",
    "# from sklearn.externals import joblib\n",
    "import lightgbm as lgb\n",
    "from sklearn.metrics import roc_auc_score\n",
    "from random import random\n",
    "from lightgbm import LGBMClassifier\n",
    "from sklearn.model_selection import KFold\n",
    "\n",
    "pd.set_option('display.max_columns',None) \n",
    "pd.set_option('expand_frame_repr', False)\n",
    "\n",
    "#我的多核函数，可以提高训练速度，考虑到总行复现环境不确定性，就没有用\n",
    "def applyParallel(dfGrouped, func):\n",
    "    ret = Parallel(n_jobs=multiprocessing.cpu_count()-6)(delayed(func)(name,group) for name, group in dfGrouped)\n",
    "    return pd.concat(ret)\n",
    "\n",
    "#调参类定义，传入多个参数组成的一个字典，返回一个迭代器，感觉比sklearn中的调参函数好用，个人习惯吧\n",
    "class params_iter:\n",
    "    def getPlans(self,lis,jude=True):\n",
    "        if jude: \n",
    "            lis = [[[i] for i in lis[0]]] + lis[1:]\n",
    "        if len(lis) > 2:\n",
    "            for i in lis[0]:\n",
    "                for j in lis[1]:\n",
    "                    self.getPlans([[i + [j]]] + lis[2:], False)\n",
    "        elif len(lis) == 2:\n",
    "            for i in lis[0]:\n",
    "                for j in lis[1]:\n",
    "                    self.param_list.append(i + [j])\n",
    "                \n",
    "    def __init__(self,params):\n",
    "        self.params=params\n",
    "        self.cur_index=0\n",
    "        self.param_list=[]\n",
    "        val=list(params.values())\n",
    "        keys=list(params.keys())\n",
    "        self.getPlans(val)\n",
    "        self.df=pd.DataFrame(self.param_list,columns=keys)\n",
    "        \n",
    "    def __iter__(self):\n",
    "        return self\n",
    " \n",
    "    def __next__(self):\n",
    "        if self.df.shape[0]==self.cur_index:\n",
    "            raise StopIteration\n",
    "        x = self.df.iloc[self.cur_index,:]\n",
    "        self.cur_index += 1\n",
    "        return x.to_dict()\n",
    "    \n",
    "def get_sample(dataset,target_0=0.33,target_1=0.33,seed=None):\n",
    "    dataset=dataset.copy()\n",
    "    x0=dataset[dataset['target']==0]\n",
    "    x1=dataset[dataset['target']==1]\n",
    "    x0_selected=x0.sample(frac=target_0,random_state=seed)\n",
    "    x1_selected=x1.sample(frac=target_1,random_state=seed)\n",
    "    dataset=pd.concat([x0_selected,x1_selected]).sample(frac=1,random_state=seed)\n",
    "    y_selected=dataset['target']\n",
    "    x_selected=dataset.drop(columns =['target'])\n",
    "    return x_selected,y_selected\n",
    "def cv(dataset_x,dataset_y,model,k=5, **fit_params) : \n",
    "    models=[]\n",
    "    dataset_x=dataset_x.values\n",
    "    dataset_y=dataset_y.values\n",
    "    kf = KFold(n_splits=k,random_state=0)\n",
    "    def run(train_index, test_index,model, **fit_params):\n",
    "        X_train,X_eval = dataset_x[train_index], dataset_x[test_index]\n",
    "        Y_train,Y_eval = dataset_y[train_index], dataset_y[test_index]\n",
    "\n",
    "        model=model.fit(X_train,Y_train,eval_set=(X_eval,Y_eval),eval_metric='auc',early_stopping_rounds=200, **fit_params)\n",
    "        return model,model.best_score_['valid_0']['auc']\n",
    "    \n",
    "    re=Parallel(n_jobs=3)(delayed(run)(train_index, test_index,model, **fit_params) for train_index, test_index in kf.split(dataset_x))\n",
    "    models=pd.DataFrame(re)[0].to_list()\n",
    "    avg_score=pd.DataFrame(re)[1].mean()\n",
    "    return models,avg_score\n",
    "\n",
    "def predict(X_test,models):\n",
    "    def run(model):\n",
    "        y_pr=model.predict_proba(X_test)[:,1]\n",
    "        return y_pr\n",
    "    y_pres=Parallel(n_jobs=40)(delayed(run)(model) for model in models)\n",
    "    y_pres=pd.DataFrame(np.array(y_pres).T)\n",
    "    y_pr=y_pres.mean(axis=1)\n",
    "    y_pr.index=X_test.index\n",
    "    return y_pr\n",
    "def add_log(auc,feature,models):\n",
    "    f=open('log.txt','a+')\n",
    "    s=str(auc) +'\\r\\n'+str(feature)+'\\r\\n' +str(models) +'\\r\\n'\n",
    "    f.write(s)\n",
    "    f.close()\n",
    "def get_feature():\n",
    "    drop_feature=['k_mdivision_tranbal','target','index']\n",
    "    cago_feature=['crcd_is_overdue', 'cus_sex', 'crcd_is_pc_0', 'crcd_is_pc_1', 'crcd_is_pc_2', 'crcd_is_sup_0', 'crcd_is_sup_1', 'crcd_is_sup_2', 'cus_type_0', 'cus_type_1', 'cus_type_2', 'crcd_is_gec_0', 'crcd_is_gec_1', 'crcd_is_gec_2', 'crcd_bachange_cnt_0', 'crcd_bachange_cnt_1', 'crcd_bachange_cnt_2', 'crcd_bachange_cnt_3', 'cus_intvtime_trans_0', 'cus_intvtime_trans_1', 'cus_intvtime_trans_2', 'cus_intvtime_trans_3', 'cus_intvtime_trans_4', 'cus_edu_0', 'cus_edu_1', 'cus_edu_2', 'cus_edu_3', 'cus_edu_4', 'cus_edu_5', 'cus_marr_stat_0', 'cus_marr_stat_1', 'cus_marr_stat_2', 'cus_marr_stat_3', 'cus_occu_0', 'cus_occu_1', 'cus_occu_2', 'cus_occu_3', 'cus_occu_4', 'cus_occu_5', 'cus_occu_6', 'cus_occu_7', 'cus_occu_8', 'cus_occu_9', 'cus_occu_10', 'cus_occu_11', 'cus_occu_12', 'cus_occu_13', 'cus_occu_14', 'cus_occu_15', 'cus_occu_16', 'cus_occu_17', 'cus_occu_18', 'cus_occu_19', 'cus_occu_20', 'cus_occu_21', 'cus_occu_22', 'cus_occu_23', 'cus_occu_24', 'cus_occu_25', 'cus_occu_26', 'cus_occu_27', 'cus_occu_28', 'cus_occu_29', 'cus_occu_30', 'cus_occu_31', 'cus_occu_32', 'cus_occu_33', 'cus_occu_34', 'cus_occu_35', 'cus_oact_pla_0', 'cus_oact_pla_1', 'cus_oact_pla_2', 'cus_oact_pla_3', 'cus_oact_pla_4', 'cus_oact_pla_5', 'cus_oact_pla_6', 'cus_oact_pla_7', 'cus_oact_pla_8', 'cus_oact_pla_9', 'cus_oact_pla_10', 'cus_oact_pla_11', 'cus_oact_pla_12', 'cus_oact_pla_13', 'cus_oact_pla_14', 'cus_oact_pla_15', 'cus_oact_pla_16', 'cus_oact_pla_17', 'cus_oact_pla_18', 'cus_oact_pla_19', 'cus_oact_pla_20', 'cus_oact_pla_21', 'cus_oact_pla_22', 'cus_oact_pla_23', 'cus_oact_pla_24', 'cus_oact_pla_25', 'cus_oact_pla_26', 'cus_oact_pla_27', 'cus_oact_pla_28', 'cus_oact_pla_29', 'cus_oact_pla_30', 'cus_oact_pla_31', 'cus_oact_pla_32', 'cus_oact_pla_33', 'cus_oact_pla_34', 'cus_oact_pla_35', 'cus_oact_pla_36', 'cus_oact_pla_37', 'cus_oact_pla_38', 'cus_oact_pla_39', 'cus_oact_pla_40', 'cus_oact_pla_41', 'cus_oact_pla_42', 'cus_oact_pla_43', 'cus_oact_pla_44', 'cus_oact_pla_45', 'cus_oact_pla_46', 'cus_oact_pla_47', 'cus_oact_pla_48', 'cus_oact_pla_49', 'cus_oact_pla_50', 'cus_oact_pla_51', 'cus_oact_pla_52', 'cus_oact_pla_53', 'cus_oact_pla_54', 'cus_os_dist_0', 'cus_os_dist_1', 'cus_os_dist_2', 'cus_os_dist_3', 'cus_os_dist_4', 'cus_os_dist_5', 'cus_os_dist_6', 'cus_os_dist_7', 'cus_os_dist_8', 'cus_os_dist_9', 'cus_os_dist_10', 'cus_os_dist_11', 'cus_os_dist_12', 'cus_os_dist_13', 'cus_os_dist_14', 'cus_os_dist_15', 'cus_os_dist_16', 'cus_os_dist_17', 'cus_os_dist_18', 'cus_os_dist_19', 'cus_os_dist_20', 'cus_os_dist_21', 'cus_os_dist_22', 'cus_os_dist_23', 'cus_os_dist_24', 'cus_os_dist_25', 'cus_os_dist_26', 'cus_os_dist_27', 'cus_os_dist_28', 'cus_os_dist_29', 'cus_os_dist_30', 'cus_os_dist_31', 'cus_os_dist_32', 'cus_os_dist_33', 'cus_os_dist_34', 'cus_os_dist_35', 'cus_os_dist_36', 'cus_os_dist_37', 'cus_os_dist_38', 'cus_os_dist_39', 'cus_os_dist_40', 'cus_os_dist_41', 'cus_os_dist_42', 'cus_os_dist_43', 'cus_os_dist_44', 'cus_os_dist_45', 'cus_os_dist_46', 'cus_os_dist_47', 'cus_os_dist_48', 'cus_os_dist_49', 'cus_os_dist_50', 'cus_os_dist_51', 'cus_os_dist_52', 'cus_os_dist_53', 'cus_os_dist_54', 'cus_os_dist_55', 'crcd_is_gc_0', 'crcd_is_gc_1', 'crcd_is_gc_2', 'crcd_bill_mcnt_0', 'crcd_bill_mcnt_1', 'crcd_bill_mcnt_2', 'crcd_bill_mcnt_3', 'crcd_bill_mcnt_4', 'crcd_bill_mcnt_5', 'crcd_bill_mcnt_6', 'crcd_bill_mcnt_7', 'crcd_bill_mcnt_8', 'crcd_bill_mcnt_9', 'crcd_bill_mcnt_10', 'crcd_bill_mcnt_11', 'crcd_bill_mcnt_12', 'crcd_bill_mcnt_13', 'crcd_bill_mcnt_14', 'crcd_bill_mcnt_15', 'crcd_bill_mcnt_16', 'crcd_bill_mcnt_17', 'crcd_bill_mcnt_18', 'crcd_bill_mcnt_19', 'crcd_bill_mcnt_20', 'crcd_bill_mcnt_21', 'crcd_bill_mcnt_22', 'crcd_bill_mcnt_23', 'crcd_bill_mcnt_24', 'crcd_bill_mcnt_25', 'crcd_bill_mcnt_26', 'crcd_bill_mcnt_27']\n",
    "    continue_feature=['cus_age', 'cus_mbank_lcnt', 'cus_active_ind', 'pass_date', 'interval_mon_count', 'interval_date_1stc', 'interval_date_1stc12', 'cus_hisloan_cnt', 'crcd_mavg_balind', 'cus_region_move_ind', 'cus_reloan_cap_ind', 'cus_asset_bal', 'crcd_max_quota', 'crcd_lmon_due_amount', 'crcd_due_amount', 'crcd_mavg_balance', 'crcd_points', 'a_mmax_tranbal', 'a_mavg_tranbal', 'b_mmax_tranbal', 'b_mavg_tranbal', 'c_mmax_tranbal', 'c_mavg_tranbal', 'd_mmax_tranbal', 'd_mavg_tranbal', 'e_mmax_tranbal', 'e_mavg_tranbal', 'f_mmax_tranbal', 'f_mavg_tranbal', 'g_mmax_tranbal', 'g_mavg_tranbal', 'h_mmax_tranbal', 'h_mavg_tranbal', 'i_mmax_tranbal', 'i_mavg_tranbal', 'j_mmax_tranbal', 'j_mavg_tranbal', 'k_mmax_tranbal', 'k_mavg_tranbal', 'm_mmax_tranbal', 'm_mavg_tranbal', 'n_mavg_trancount', 'n_mavg_tranbal', 'a_mdivision_tranbal', 'b_mdivision_tranbal', 'c_mdivision_tranbal', 'd_mdivision_tranbal', 'e_mdivision_tranbal', 'f_mdivision_tranbal', 'g_mdivision_tranbal', 'h_mdivision_tranbal', 'i_mdivision_tranbal', 'j_mdivision_tranbal', 'm_mdivision_tranbal', 'n_mdivision_tranbal', 'a_div_cus_asset_bal', 'b_div_cus_asset_bal', 'c_div_cus_asset_bal', 'd_div_cus_asset_bal', 'e_div_cus_asset_bal', 'f_div_cus_asset_bal', 'g_div_cus_asset_bal', 'h_div_cus_asset_bal', 'i_div_cus_asset_bal', 'j_div_cus_asset_bal', 'k_div_cus_asset_bal', 'm_div_cus_asset_bal', 'n_div_cus_asset_bal', 'pass_date1', 'pass_date2', 'pass_date', 'interval_mon_count1', 'interval_mon_count2', 'new12', 'new13', 'new14', 'new15', 'new16', 'new17', 'new18', 'new1', 'new2', 'new3', 'new4', 'new5', 'new6', 'new7', 'new8', 'new9', 'new10', 'new11', 'crcd1', 'crcd2', 'crcd3', 'crcd4', 'crcd5', 'interval_date1', 'cus_asset_bal1', 'cus_asset_bal2', 'cus_marr_stat1']\n",
    "    return cago_feature+continue_feature\n",
    "def get_sample(dataset,target_0=0.33,target_1=0.33,seed=None):\n",
    "    dataset=dataset.copy()\n",
    "    x0=dataset[dataset['target']==0]\n",
    "    x1=dataset[dataset['target']==1]\n",
    "    x0_selected=x0.sample(frac=target_0,random_state=seed)\n",
    "    x1_selected=x1.sample(frac=target_1,random_state=seed)\n",
    "    dataset=pd.concat([x0_selected,x1_selected]).sample(frac=1,random_state=seed)\n",
    "    y_selected=dataset['target']\n",
    "    x_selected=dataset.drop(columns =['target'])\n",
    "    return x_selected,y_selected\n",
    "dataset_train=pd.read_hdf('dataset/1_1_1_1_1_one-hot.h5', key='TRAIN')\n",
    "dataset_test=pd.read_hdf('dataset/1_1_1_1_1_one-hot.h5', key='PREDICT')\n",
    "feature=get_feature()\n",
    "feature_train=feature+['target']\n",
    "feature_test=feature\n",
    "dataset_train=dataset_train[feature_train]\n",
    "dataset_test=dataset_test[feature_test]\n",
    "dataset_train_x,dataset_train_y=get_sample(dataset_train,target_0=1,target_1=1,seed=None)\n",
    "X_train,X_test,Y_train,Y_test=train_test_split(dataset_train_x,dataset_train_y,test_size=0.2,random_state=None)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "auc: 0.5234716130112846\n"
     ]
    }
   ],
   "source": [
    "from sklearn.naive_bayes import GaussianNB \n",
    "clf = GaussianNB()\n",
    "model=clf.fit(X_train,Y_train.values.ravel()) \n",
    "print('auc:',roc_auc_score(Y_test,model.predict_proba(X_test)[:,1]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(83868, 312)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "Train on 83868 samples, validate on 20968 samples\n",
      "Epoch 1/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.669031 \n",
      "\n",
      "83868/83868 - 6s - loss: 61.2623 - accuracy: 0.8982 - val_loss: 6.1425 - val_accuracy: 0.9110\n",
      "Epoch 2/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.628911 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.8360 - accuracy: 0.9114 - val_loss: 0.3464 - val_accuracy: 0.9110\n",
      "Epoch 3/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.555019 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3445 - accuracy: 0.9114 - val_loss: 0.3460 - val_accuracy: 0.9110\n",
      "Epoch 4/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.542765 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3444 - accuracy: 0.9114 - val_loss: 0.3455 - val_accuracy: 0.9110\n",
      "Epoch 5/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.622209 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3445 - accuracy: 0.9114 - val_loss: 0.3455 - val_accuracy: 0.9110\n",
      "Epoch 6/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.651908 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3446 - accuracy: 0.9114 - val_loss: 0.3453 - val_accuracy: 0.9110\n",
      "Epoch 7/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.572071 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3445 - accuracy: 0.9114 - val_loss: 0.3457 - val_accuracy: 0.9110\n",
      "Epoch 8/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.644320 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3445 - accuracy: 0.9114 - val_loss: 0.3457 - val_accuracy: 0.9110\n",
      "Epoch 9/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.650635 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3445 - accuracy: 0.9114 - val_loss: 0.3452 - val_accuracy: 0.9110\n",
      "Epoch 10/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.620236 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3446 - accuracy: 0.9114 - val_loss: 0.3456 - val_accuracy: 0.9110\n",
      "Epoch 11/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.665751 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3446 - accuracy: 0.9114 - val_loss: 0.3458 - val_accuracy: 0.9110\n",
      "Epoch 12/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.671857 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3418 - accuracy: 0.9114 - val_loss: 0.3396 - val_accuracy: 0.9110\n",
      "Epoch 13/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.675393 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3359 - accuracy: 0.9114 - val_loss: 0.3370 - val_accuracy: 0.9110\n",
      "Epoch 14/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.678411 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3333 - accuracy: 0.9114 - val_loss: 0.3344 - val_accuracy: 0.9110\n",
      "Epoch 15/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.680945 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3314 - accuracy: 0.9114 - val_loss: 0.3350 - val_accuracy: 0.9110\n",
      "Epoch 16/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.683743 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3300 - accuracy: 0.9114 - val_loss: 0.3316 - val_accuracy: 0.9110\n",
      "Epoch 17/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.685657 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3291 - accuracy: 0.9114 - val_loss: 0.3329 - val_accuracy: 0.9110\n",
      "Epoch 18/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.687592 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3281 - accuracy: 0.9114 - val_loss: 0.3318 - val_accuracy: 0.9110\n",
      "Epoch 19/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.689981 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3274 - accuracy: 0.9114 - val_loss: 0.3330 - val_accuracy: 0.9110\n",
      "Epoch 20/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.692018 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3269 - accuracy: 0.9114 - val_loss: 0.3290 - val_accuracy: 0.9110\n",
      "Epoch 21/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.694114 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3259 - accuracy: 0.9114 - val_loss: 0.3279 - val_accuracy: 0.9110\n",
      "Epoch 22/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.695802 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3253 - accuracy: 0.9114 - val_loss: 0.3260 - val_accuracy: 0.9110\n",
      "Epoch 23/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.697584 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3244 - accuracy: 0.9114 - val_loss: 0.3277 - val_accuracy: 0.9110\n",
      "Epoch 24/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.699042 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3239 - accuracy: 0.9114 - val_loss: 0.3265 - val_accuracy: 0.9110\n",
      "Epoch 25/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.700515 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3231 - accuracy: 0.9114 - val_loss: 0.3250 - val_accuracy: 0.9110\n",
      "Epoch 26/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.701894 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3226 - accuracy: 0.9114 - val_loss: 0.3242 - val_accuracy: 0.9110\n",
      "Epoch 27/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.702678 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3223 - accuracy: 0.9114 - val_loss: 0.3242 - val_accuracy: 0.9110\n",
      "Epoch 28/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.704106 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3217 - accuracy: 0.9114 - val_loss: 0.3240 - val_accuracy: 0.9110\n",
      "Epoch 29/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.704691 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3216 - accuracy: 0.9114 - val_loss: 0.3242 - val_accuracy: 0.9110\n",
      "Epoch 30/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.706088 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3209 - accuracy: 0.9114 - val_loss: 0.3228 - val_accuracy: 0.9110\n",
      "Epoch 31/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.706310 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3205 - accuracy: 0.9114 - val_loss: 0.3229 - val_accuracy: 0.9110\n",
      "Epoch 32/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.707171 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3201 - accuracy: 0.9114 - val_loss: 0.3220 - val_accuracy: 0.9110\n",
      "Epoch 33/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.707776 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3198 - accuracy: 0.9114 - val_loss: 0.3222 - val_accuracy: 0.9110\n",
      "Epoch 34/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.708439 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3197 - accuracy: 0.9114 - val_loss: 0.3226 - val_accuracy: 0.9110\n",
      "Epoch 35/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.709220 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3196 - accuracy: 0.9114 - val_loss: 0.3234 - val_accuracy: 0.9110\n",
      "Epoch 36/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.709472 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3193 - accuracy: 0.9114 - val_loss: 0.3223 - val_accuracy: 0.9110\n",
      "Epoch 37/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.709735 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3191 - accuracy: 0.9114 - val_loss: 0.3226 - val_accuracy: 0.9110\n",
      "Epoch 38/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.710136 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3189 - accuracy: 0.9114 - val_loss: 0.3213 - val_accuracy: 0.9110\n",
      "Epoch 39/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.710690 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3188 - accuracy: 0.9114 - val_loss: 0.3218 - val_accuracy: 0.9110\n",
      "Epoch 40/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.710268 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3186 - accuracy: 0.9114 - val_loss: 0.3213 - val_accuracy: 0.9110\n",
      "Epoch 41/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.710788 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3186 - accuracy: 0.9114 - val_loss: 0.3216 - val_accuracy: 0.9110\n",
      "Epoch 42/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.711389 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3183 - accuracy: 0.9114 - val_loss: 0.3210 - val_accuracy: 0.9110\n",
      "Epoch 43/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.711779 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3182 - accuracy: 0.9114 - val_loss: 0.3211 - val_accuracy: 0.9110\n",
      "Epoch 44/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.711574 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3182 - accuracy: 0.9114 - val_loss: 0.3212 - val_accuracy: 0.9110\n",
      "Epoch 45/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.711821 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3180 - accuracy: 0.9114 - val_loss: 0.3200 - val_accuracy: 0.9110\n",
      "Epoch 46/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712132 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3178 - accuracy: 0.9114 - val_loss: 0.3207 - val_accuracy: 0.9110\n",
      "Epoch 47/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712094 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3175 - accuracy: 0.9114 - val_loss: 0.3200 - val_accuracy: 0.9110\n",
      "Epoch 48/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712424 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3173 - accuracy: 0.9114 - val_loss: 0.3202 - val_accuracy: 0.9110\n",
      "Epoch 49/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712613 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3172 - accuracy: 0.9114 - val_loss: 0.3204 - val_accuracy: 0.9110\n",
      "Epoch 50/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712729 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3171 - accuracy: 0.9114 - val_loss: 0.3209 - val_accuracy: 0.9110\n",
      "Epoch 51/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712763 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3170 - accuracy: 0.9114 - val_loss: 0.3211 - val_accuracy: 0.9110\n",
      "Epoch 52/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712591 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3169 - accuracy: 0.9114 - val_loss: 0.3208 - val_accuracy: 0.9110\n",
      "Epoch 53/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712957 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3169 - accuracy: 0.9114 - val_loss: 0.3202 - val_accuracy: 0.9110\n",
      "Epoch 54/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713334 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3169 - accuracy: 0.9114 - val_loss: 0.3205 - val_accuracy: 0.9110\n",
      "Epoch 55/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712960 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3168 - accuracy: 0.9114 - val_loss: 0.3204 - val_accuracy: 0.9110\n",
      "Epoch 56/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713890 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3167 - accuracy: 0.9114 - val_loss: 0.3208 - val_accuracy: 0.9110\n",
      "Epoch 57/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713729 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3167 - accuracy: 0.9114 - val_loss: 0.3208 - val_accuracy: 0.9110\n",
      "Epoch 58/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713485 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3166 - accuracy: 0.9114 - val_loss: 0.3204 - val_accuracy: 0.9110\n",
      "Epoch 59/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713854 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3165 - accuracy: 0.9114 - val_loss: 0.3200 - val_accuracy: 0.9110\n",
      "Epoch 60/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713703 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3164 - accuracy: 0.9114 - val_loss: 0.3203 - val_accuracy: 0.9110\n",
      "Epoch 61/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714247 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3164 - accuracy: 0.9114 - val_loss: 0.3202 - val_accuracy: 0.9110\n",
      "Epoch 62/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714710 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3163 - accuracy: 0.9114 - val_loss: 0.3198 - val_accuracy: 0.9110\n",
      "Epoch 63/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714415 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3161 - accuracy: 0.9114 - val_loss: 0.3207 - val_accuracy: 0.9110\n",
      "Epoch 64/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714612 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3162 - accuracy: 0.9114 - val_loss: 0.3203 - val_accuracy: 0.9110\n",
      "Epoch 65/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714898 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3160 - accuracy: 0.9114 - val_loss: 0.3196 - val_accuracy: 0.9110\n",
      "Epoch 66/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714686 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3160 - accuracy: 0.9114 - val_loss: 0.3197 - val_accuracy: 0.9110\n",
      "Epoch 67/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714958 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3159 - accuracy: 0.9114 - val_loss: 0.3204 - val_accuracy: 0.9110\n",
      "Epoch 68/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715139 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3160 - accuracy: 0.9114 - val_loss: 0.3210 - val_accuracy: 0.9110\n",
      "Epoch 69/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715630 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3157 - accuracy: 0.9114 - val_loss: 0.3207 - val_accuracy: 0.9110\n",
      "Epoch 70/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715218 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3159 - accuracy: 0.9114 - val_loss: 0.3196 - val_accuracy: 0.9110\n",
      "Epoch 71/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715081 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3155 - accuracy: 0.9114 - val_loss: 0.3204 - val_accuracy: 0.9110\n",
      "Epoch 72/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715122 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3155 - accuracy: 0.9114 - val_loss: 0.3208 - val_accuracy: 0.9110\n",
      "Epoch 73/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715277 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3154 - accuracy: 0.9114 - val_loss: 0.3210 - val_accuracy: 0.9110\n",
      "Epoch 74/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715963 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3154 - accuracy: 0.9114 - val_loss: 0.3197 - val_accuracy: 0.9110\n",
      "Epoch 75/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715595 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3154 - accuracy: 0.9114 - val_loss: 0.3220 - val_accuracy: 0.9110\n",
      "Epoch 76/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716570 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3155 - accuracy: 0.9114 - val_loss: 0.3202 - val_accuracy: 0.9110\n",
      "Epoch 77/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715625 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3151 - accuracy: 0.9114 - val_loss: 0.3218 - val_accuracy: 0.9110\n",
      "Epoch 78/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715968 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3151 - accuracy: 0.9114 - val_loss: 0.3220 - val_accuracy: 0.9110\n",
      "Epoch 79/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716856 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3150 - accuracy: 0.9114 - val_loss: 0.3201 - val_accuracy: 0.9110\n",
      "Epoch 80/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717168 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3147 - accuracy: 0.9114 - val_loss: 0.3212 - val_accuracy: 0.9110\n",
      "Epoch 81/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717324 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3146 - accuracy: 0.9114 - val_loss: 0.3200 - val_accuracy: 0.9110\n",
      "Epoch 82/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717434 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3145 - accuracy: 0.9114 - val_loss: 0.3217 - val_accuracy: 0.9110\n",
      "Epoch 83/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717593 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3144 - accuracy: 0.9114 - val_loss: 0.3210 - val_accuracy: 0.9110\n",
      "Epoch 84/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717077 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3142 - accuracy: 0.9114 - val_loss: 0.3219 - val_accuracy: 0.9110\n",
      "Epoch 85/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717183 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3141 - accuracy: 0.9114 - val_loss: 0.3216 - val_accuracy: 0.9110\n",
      "Epoch 86/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717360 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3141 - accuracy: 0.9114 - val_loss: 0.3209 - val_accuracy: 0.9110\n",
      "Epoch 87/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717574 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3136 - accuracy: 0.9114 - val_loss: 0.3221 - val_accuracy: 0.9110\n",
      "Epoch 88/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716465 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3137 - accuracy: 0.9114 - val_loss: 0.3217 - val_accuracy: 0.9110\n",
      "Epoch 89/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717211 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3135 - accuracy: 0.9114 - val_loss: 0.3227 - val_accuracy: 0.9110\n",
      "Epoch 90/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716793 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3134 - accuracy: 0.9114 - val_loss: 0.3237 - val_accuracy: 0.9110\n",
      "Epoch 91/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716320 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3130 - accuracy: 0.9114 - val_loss: 0.3232 - val_accuracy: 0.9110\n",
      "Epoch 92/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.718121 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3128 - accuracy: 0.9114 - val_loss: 0.3218 - val_accuracy: 0.9110\n",
      "Epoch 93/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.717132 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3127 - accuracy: 0.9114 - val_loss: 0.3232 - val_accuracy: 0.9110\n",
      "Epoch 94/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716599 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3122 - accuracy: 0.9114 - val_loss: 0.3232 - val_accuracy: 0.9110\n",
      "Epoch 95/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716645 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3120 - accuracy: 0.9114 - val_loss: 0.3243 - val_accuracy: 0.9110\n",
      "Epoch 96/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716552 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3119 - accuracy: 0.9114 - val_loss: 0.3245 - val_accuracy: 0.9110\n",
      "Epoch 97/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716574 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3117 - accuracy: 0.9114 - val_loss: 0.3258 - val_accuracy: 0.9110\n",
      "Epoch 98/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716654 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3115 - accuracy: 0.9114 - val_loss: 0.3240 - val_accuracy: 0.9110\n",
      "Epoch 99/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715911 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3111 - accuracy: 0.9114 - val_loss: 0.3256 - val_accuracy: 0.9110\n",
      "Epoch 100/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716373 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3108 - accuracy: 0.9114 - val_loss: 0.3264 - val_accuracy: 0.9110\n",
      "Epoch 101/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.714348 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3106 - accuracy: 0.9114 - val_loss: 0.3261 - val_accuracy: 0.9110\n",
      "Epoch 102/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.716456 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3101 - accuracy: 0.9114 - val_loss: 0.3265 - val_accuracy: 0.9110\n",
      "Epoch 103/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.715509 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3095 - accuracy: 0.9114 - val_loss: 0.3275 - val_accuracy: 0.9110\n",
      "Epoch 104/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713570 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3098 - accuracy: 0.9114 - val_loss: 0.3294 - val_accuracy: 0.9110\n",
      "Epoch 105/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.711714 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3089 - accuracy: 0.9115 - val_loss: 0.3273 - val_accuracy: 0.9110\n",
      "Epoch 106/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713001 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3087 - accuracy: 0.9117 - val_loss: 0.3291 - val_accuracy: 0.9110\n",
      "Epoch 107/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713764 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3083 - accuracy: 0.9119 - val_loss: 0.3286 - val_accuracy: 0.9100\n",
      "Epoch 108/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.712120 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3079 - accuracy: 0.9120 - val_loss: 0.3281 - val_accuracy: 0.9110\n",
      "Epoch 109/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.713558 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3076 - accuracy: 0.9118 - val_loss: 0.3294 - val_accuracy: 0.9105\n",
      "Epoch 110/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.711019 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3073 - accuracy: 0.9120 - val_loss: 0.3311 - val_accuracy: 0.9100\n",
      "Epoch 111/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.706768 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3063 - accuracy: 0.9122 - val_loss: 0.3328 - val_accuracy: 0.9103\n",
      "Epoch 112/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.708299 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3059 - accuracy: 0.9125 - val_loss: 0.3334 - val_accuracy: 0.9110\n",
      "Epoch 113/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.709842 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3057 - accuracy: 0.9123 - val_loss: 0.3327 - val_accuracy: 0.9107\n",
      "Epoch 114/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.710856 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3051 - accuracy: 0.9125 - val_loss: 0.3336 - val_accuracy: 0.9105\n",
      "Epoch 115/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.705194 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3044 - accuracy: 0.9126 - val_loss: 0.3345 - val_accuracy: 0.9101\n",
      "Epoch 116/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.707187 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3036 - accuracy: 0.9126 - val_loss: 0.3351 - val_accuracy: 0.9101\n",
      "Epoch 117/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.707642 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3033 - accuracy: 0.9130 - val_loss: 0.3373 - val_accuracy: 0.9098\n",
      "Epoch 118/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.707280 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3023 - accuracy: 0.9130 - val_loss: 0.3414 - val_accuracy: 0.9103\n",
      "Epoch 119/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.697741 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3019 - accuracy: 0.9132 - val_loss: 0.3413 - val_accuracy: 0.9084\n",
      "Epoch 120/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.700973 \n",
      "\n",
      "83868/83868 - 6s - loss: 0.3013 - accuracy: 0.9132 - val_loss: 0.3409 - val_accuracy: 0.9101\n",
      "Epoch 121/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.694458 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.3001 - accuracy: 0.9137 - val_loss: 0.3453 - val_accuracy: 0.9074\n",
      "Epoch 122/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.699580 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2994 - accuracy: 0.9133 - val_loss: 0.3428 - val_accuracy: 0.9100\n",
      "Epoch 123/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.698106 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2988 - accuracy: 0.9137 - val_loss: 0.3453 - val_accuracy: 0.9082\n",
      "Epoch 124/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.701024 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2976 - accuracy: 0.9141 - val_loss: 0.3467 - val_accuracy: 0.9080\n",
      "Epoch 125/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.694189 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2970 - accuracy: 0.9149 - val_loss: 0.3484 - val_accuracy: 0.9079\n",
      "Epoch 126/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.693205 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2960 - accuracy: 0.9147 - val_loss: 0.3501 - val_accuracy: 0.9068\n",
      "Epoch 127/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.693258 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2949 - accuracy: 0.9149 - val_loss: 0.3516 - val_accuracy: 0.9091\n",
      "Epoch 128/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.683844 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2941 - accuracy: 0.9156 - val_loss: 0.3592 - val_accuracy: 0.9029\n",
      "Epoch 129/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.685065 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2929 - accuracy: 0.9159 - val_loss: 0.3532 - val_accuracy: 0.9083\n",
      "Epoch 130/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.682943 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2915 - accuracy: 0.9164 - val_loss: 0.3584 - val_accuracy: 0.9078\n",
      "Epoch 131/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.687934 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2907 - accuracy: 0.9172 - val_loss: 0.3567 - val_accuracy: 0.9070\n",
      "Epoch 132/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.679164 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2887 - accuracy: 0.9173 - val_loss: 0.3681 - val_accuracy: 0.9058\n",
      "Epoch 133/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.685168 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2881 - accuracy: 0.9177 - val_loss: 0.3649 - val_accuracy: 0.9030\n",
      "Epoch 134/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.683606 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2861 - accuracy: 0.9185 - val_loss: 0.3723 - val_accuracy: 0.8985\n",
      "Epoch 135/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.671920 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2850 - accuracy: 0.9189 - val_loss: 0.3742 - val_accuracy: 0.9007\n",
      "Epoch 136/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.668436 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2828 - accuracy: 0.9201 - val_loss: 0.3724 - val_accuracy: 0.9035\n",
      "Epoch 137/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.674136 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2818 - accuracy: 0.9204 - val_loss: 0.3803 - val_accuracy: 0.8979\n",
      "Epoch 138/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.671097 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2805 - accuracy: 0.9210 - val_loss: 0.3806 - val_accuracy: 0.8979\n",
      "Epoch 139/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.676941 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2782 - accuracy: 0.9222 - val_loss: 0.3839 - val_accuracy: 0.8969\n",
      "Epoch 140/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.673064 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2763 - accuracy: 0.9224 - val_loss: 0.3859 - val_accuracy: 0.8997\n",
      "Epoch 141/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.666765 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2744 - accuracy: 0.9236 - val_loss: 0.3887 - val_accuracy: 0.9034\n",
      "Epoch 142/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.669912 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2729 - accuracy: 0.9246 - val_loss: 0.3947 - val_accuracy: 0.9040\n",
      "Epoch 143/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.669518 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2706 - accuracy: 0.9254 - val_loss: 0.4009 - val_accuracy: 0.8919\n",
      "Epoch 144/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.657636 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2685 - accuracy: 0.9270 - val_loss: 0.4013 - val_accuracy: 0.9012\n",
      "Epoch 145/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.658126 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2662 - accuracy: 0.9284 - val_loss: 0.4086 - val_accuracy: 0.9005\n",
      "Epoch 146/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.671225 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2646 - accuracy: 0.9290 - val_loss: 0.4063 - val_accuracy: 0.8958\n",
      "Epoch 147/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.658647 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2621 - accuracy: 0.9305 - val_loss: 0.4130 - val_accuracy: 0.8987\n",
      "Epoch 148/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.668377 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2591 - accuracy: 0.9321 - val_loss: 0.4193 - val_accuracy: 0.8887\n",
      "Epoch 149/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.657158 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2571 - accuracy: 0.9330 - val_loss: 0.4196 - val_accuracy: 0.8914\n",
      "Epoch 150/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.653434 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2545 - accuracy: 0.9341 - val_loss: 0.4284 - val_accuracy: 0.8930\n",
      "Epoch 151/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.658721 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2520 - accuracy: 0.9355 - val_loss: 0.4352 - val_accuracy: 0.9007\n",
      "Epoch 152/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.653846 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2497 - accuracy: 0.9366 - val_loss: 0.4368 - val_accuracy: 0.8904\n",
      "Epoch 153/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.653899 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2468 - accuracy: 0.9382 - val_loss: 0.4404 - val_accuracy: 0.8913\n",
      "Epoch 154/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.644582 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2434 - accuracy: 0.9398 - val_loss: 0.4450 - val_accuracy: 0.8822\n",
      "Epoch 155/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.655356 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2411 - accuracy: 0.9413 - val_loss: 0.4537 - val_accuracy: 0.8957\n",
      "Epoch 156/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.642875 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2381 - accuracy: 0.9431 - val_loss: 0.4551 - val_accuracy: 0.8898\n",
      "Epoch 157/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.642265 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2354 - accuracy: 0.9439 - val_loss: 0.4618 - val_accuracy: 0.8893\n",
      "Epoch 158/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.636123 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2328 - accuracy: 0.9460 - val_loss: 0.4673 - val_accuracy: 0.8877\n",
      "Epoch 159/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.646081 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2295 - accuracy: 0.9464 - val_loss: 0.4717 - val_accuracy: 0.8856\n",
      "Epoch 160/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.656203 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2261 - accuracy: 0.9481 - val_loss: 0.4822 - val_accuracy: 0.8934\n",
      "Epoch 161/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.646852 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2238 - accuracy: 0.9500 - val_loss: 0.4866 - val_accuracy: 0.8836\n",
      "Epoch 162/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.642432 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2206 - accuracy: 0.9517 - val_loss: 0.4873 - val_accuracy: 0.8874\n",
      "Epoch 163/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.645729 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2177 - accuracy: 0.9526 - val_loss: 0.4987 - val_accuracy: 0.8878\n",
      "Epoch 164/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.640088 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2150 - accuracy: 0.9544 - val_loss: 0.5049 - val_accuracy: 0.8835\n",
      "Epoch 165/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.640127 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2122 - accuracy: 0.9557 - val_loss: 0.5113 - val_accuracy: 0.8800\n",
      "Epoch 166/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.645512 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2093 - accuracy: 0.9573 - val_loss: 0.5241 - val_accuracy: 0.8889\n",
      "Epoch 167/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.646109 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2056 - accuracy: 0.9589 - val_loss: 0.5291 - val_accuracy: 0.8737\n",
      "Epoch 168/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.643212 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2035 - accuracy: 0.9594 - val_loss: 0.5301 - val_accuracy: 0.8845\n",
      "Epoch 169/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.646822 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.2001 - accuracy: 0.9618 - val_loss: 0.5421 - val_accuracy: 0.8826\n",
      "Epoch 170/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.643184 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1977 - accuracy: 0.9625 - val_loss: 0.5463 - val_accuracy: 0.8816\n",
      "Epoch 171/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.639553 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1938 - accuracy: 0.9644 - val_loss: 0.5527 - val_accuracy: 0.8724\n",
      "Epoch 172/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.632696 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1905 - accuracy: 0.9663 - val_loss: 0.5620 - val_accuracy: 0.8681\n",
      "Epoch 173/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.643197 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1880 - accuracy: 0.9675 - val_loss: 0.5711 - val_accuracy: 0.8779\n",
      "Epoch 174/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.636526 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1853 - accuracy: 0.9690 - val_loss: 0.5778 - val_accuracy: 0.8605\n",
      "Epoch 175/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.639664 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1823 - accuracy: 0.9701 - val_loss: 0.5901 - val_accuracy: 0.8808\n",
      "Epoch 176/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.640679 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1785 - accuracy: 0.9714 - val_loss: 0.5961 - val_accuracy: 0.8812\n",
      "Epoch 177/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.639515 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1772 - accuracy: 0.9722 - val_loss: 0.6044 - val_accuracy: 0.8800\n",
      "Epoch 178/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.641136 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1734 - accuracy: 0.9741 - val_loss: 0.6091 - val_accuracy: 0.8715\n",
      "Epoch 179/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.630071 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1707 - accuracy: 0.9752 - val_loss: 0.6192 - val_accuracy: 0.8668\n",
      "Epoch 180/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.643564 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1705 - accuracy: 0.9758 - val_loss: 0.6363 - val_accuracy: 0.8853\n",
      "Epoch 181/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.632595 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1652 - accuracy: 0.9779 - val_loss: 0.6323 - val_accuracy: 0.8700\n",
      "Epoch 182/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.640072 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1626 - accuracy: 0.9789 - val_loss: 0.6420 - val_accuracy: 0.8786\n",
      "Epoch 183/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.639235 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1599 - accuracy: 0.9800 - val_loss: 0.6444 - val_accuracy: 0.8707\n",
      "Epoch 184/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.630612 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1577 - accuracy: 0.9808 - val_loss: 0.6488 - val_accuracy: 0.8659\n",
      "Epoch 185/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.637554 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1545 - accuracy: 0.9819 - val_loss: 0.6700 - val_accuracy: 0.8735\n",
      "Epoch 186/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.640463 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1529 - accuracy: 0.9830 - val_loss: 0.6772 - val_accuracy: 0.8773\n",
      "Epoch 187/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.634988 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1502 - accuracy: 0.9840 - val_loss: 0.6858 - val_accuracy: 0.8778\n",
      "Epoch 188/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.627225 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1482 - accuracy: 0.9845 - val_loss: 0.6869 - val_accuracy: 0.8744\n",
      "Epoch 189/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.640152 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1454 - accuracy: 0.9852 - val_loss: 0.6906 - val_accuracy: 0.8662\n",
      "Epoch 190/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.634750 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1435 - accuracy: 0.9861 - val_loss: 0.6951 - val_accuracy: 0.8691\n",
      "Epoch 191/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.631923 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1411 - accuracy: 0.9870 - val_loss: 0.7141 - val_accuracy: 0.8648\n",
      "Epoch 192/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.641048 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1403 - accuracy: 0.9871 - val_loss: 0.7284 - val_accuracy: 0.8778\n",
      "Epoch 193/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.638256 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1369 - accuracy: 0.9880 - val_loss: 0.7237 - val_accuracy: 0.8678\n",
      "Epoch 194/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.635487 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1354 - accuracy: 0.9891 - val_loss: 0.7433 - val_accuracy: 0.8763\n",
      "Epoch 195/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.638697 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1342 - accuracy: 0.9894 - val_loss: 0.7397 - val_accuracy: 0.8710\n",
      "Epoch 196/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.635028 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1314 - accuracy: 0.9904 - val_loss: 0.7404 - val_accuracy: 0.8741\n",
      "Epoch 197/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.643263 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1304 - accuracy: 0.9904 - val_loss: 0.7697 - val_accuracy: 0.8729\n",
      "Epoch 198/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.635635 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1290 - accuracy: 0.9906 - val_loss: 0.7573 - val_accuracy: 0.8599\n",
      "Epoch 199/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.634992 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1284 - accuracy: 0.9908 - val_loss: 0.7759 - val_accuracy: 0.8792\n",
      "Epoch 200/200\n",
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "\n",
      " ROC_AUC:0.634031 \n",
      "\n",
      "83868/83868 - 5s - loss: 0.1242 - accuracy: 0.9925 - val_loss: 0.7730 - val_accuracy: 0.8776\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<tensorflow.python.keras.callbacks.History at 0x7f831f6f4b50>"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from tensorflow.keras.models import Sequential,load_model\n",
    "from tensorflow.keras.layers import Dense,Dropout\n",
    "from tensorflow.keras.callbacks import Callback\n",
    "from tensorflow.keras import regularizers\n",
    "import tensorflow as tf\n",
    "from tensorflow import keras\n",
    "\n",
    "class RocAucEvaluation(Callback):\n",
    "    def __init__(self, validation_data=(), interval=1):\n",
    "        super(Callback, self).__init__()\n",
    "        self.interval = interval\n",
    "        self.x_val,self.y_val = validation_data\n",
    "    def on_epoch_end(self, epoch, log={}):\n",
    "         if epoch % self.interval == 0:\n",
    "            y_pred = self.model.predict(self.x_val, verbose=0)\n",
    "            score = roc_auc_score(self.y_val, y_pred)\n",
    "            s=str(score)[0:7]+'_'+str(epoch)\n",
    "            model.save('models/dnns/'+s+'.h5')\n",
    "            print('\\n ROC_AUC:%.6f \\n' % score)\n",
    "            return score\n",
    "#             if score>0.87:\n",
    "#                 model.save('model/dnn/'+s+'.h5')\n",
    "RocAuc = RocAucEvaluation(validation_data=(X_test, Y_test),interval=1)\n",
    "    \n",
    "model = Sequential()\n",
    "model.add(Dense(units=600, activation='relu', input_dim=312\n",
    "                ))\n",
    "model.add(Dense(units=300,activation='relu',\n",
    "                kernel_regularizer=regularizers.l1(0.02)\n",
    "\n",
    "               ))\n",
    "# model.add(Dropout(0.2))\n",
    "model.add(Dense(units=100,activation='relu'))\n",
    "model.add(Dense(units=1, activation='sigmoid'))\n",
    "optimizer=keras.optimizers.Adam(learning_rate=0.0001, beta_1=0.9, beta_2=0.999, amsgrad=False)\n",
    "model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['accuracy'])\n",
    "model.fit(X_train, Y_train, batch_size=128, epochs=200, validation_data=(X_test, Y_test), callbacks=[RocAuc], verbose=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning: Overfitting detector is active, thus evaluation metric is calculated on every iteration. 'metric_period' is ignored for evaluation metric.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0:\ttest: 0.6296285\tbest: 0.6296285 (0)\ttotal: 25.6ms\tremaining: 7m 15s\n",
      "400:\ttest: 0.7165267\tbest: 0.7165486 (396)\ttotal: 15.6s\tremaining: 10m 44s\n",
      "800:\ttest: 0.7207765\tbest: 0.7207765 (800)\ttotal: 34s\tremaining: 11m 26s\n",
      "1200:\ttest: 0.7219391\tbest: 0.7219391 (1200)\ttotal: 52.5s\tremaining: 11m 30s\n",
      "Stopped by overfitting detector  (150 iterations wait)\n",
      "\n",
      "bestTest = 0.7219390884\n",
      "bestIteration = 1200\n",
      "\n",
      "Shrink model to first 1201 iterations.\n",
      "0.7219390884458466\n"
     ]
    }
   ],
   "source": [
    "import catboost\n",
    "dataset_train=pd.read_hdf('dataset/1_1_2_空值填充.h5', key='TRAIN')\n",
    "dataset_test=pd.read_hdf('dataset/1_1_2_空值填充.h5', key='PREDICT')\n",
    "feature=['crcd_is_overdue', 'cus_sex', 'crcd_is_pc', 'crcd_is_sup', 'cus_type', 'crcd_is_gec', 'crcd_bachange_cnt', 'cus_intvtime_trans',\n",
    "         'cus_edu', 'cus_marr_stat', 'cus_occu', 'cus_oact_pla', 'cus_os_dist', 'crcd_is_gc', 'crcd_bill_mcnt',\n",
    "                 \n",
    "        'cus_age', 'cus_mbank_lcnt', 'cus_active_ind', 'pass_date', 'interval_mon_count', 'interval_date_1stc', 'interval_date_1stc12', 'cus_hisloan_cnt', 'crcd_mavg_balind', 'cus_region_move_ind', 'cus_reloan_cap_ind', 'cus_asset_bal', 'crcd_max_quota', 'crcd_lmon_due_amount', 'crcd_due_amount', 'crcd_mavg_balance', 'crcd_points', 'a_mmax_tranbal', 'a_mavg_tranbal', 'b_mmax_tranbal', 'b_mavg_tranbal', 'c_mmax_tranbal', 'c_mavg_tranbal', 'd_mmax_tranbal', 'd_mavg_tranbal', 'e_mmax_tranbal', 'e_mavg_tranbal', 'f_mmax_tranbal', 'f_mavg_tranbal', 'g_mmax_tranbal', 'g_mavg_tranbal', 'h_mmax_tranbal', 'h_mavg_tranbal', 'i_mmax_tranbal', 'i_mavg_tranbal', 'j_mmax_tranbal', 'j_mavg_tranbal', 'k_mmax_tranbal', 'k_mavg_tranbal', 'm_mmax_tranbal', 'm_mavg_tranbal', 'n_mavg_trancount', 'n_mavg_tranbal', 'a_mdivision_tranbal', 'b_mdivision_tranbal', 'c_mdivision_tranbal', 'd_mdivision_tranbal', 'e_mdivision_tranbal', 'f_mdivision_tranbal', 'g_mdivision_tranbal', 'h_mdivision_tranbal', 'i_mdivision_tranbal', 'j_mdivision_tranbal', 'k_mdivision_tranbal', 'm_mdivision_tranbal', 'n_mdivision_tranbal', 'a_div_cus_asset_bal', 'b_div_cus_asset_bal', 'c_div_cus_asset_bal', 'd_div_cus_asset_bal', 'e_div_cus_asset_bal', 'f_div_cus_asset_bal', 'g_div_cus_asset_bal', 'h_div_cus_asset_bal', 'i_div_cus_asset_bal', 'j_div_cus_asset_bal', 'k_div_cus_asset_bal', 'm_div_cus_asset_bal', 'n_div_cus_asset_bal','pass_date1', 'pass_date2', 'interval_mon_count1', 'interval_mon_count2', 'new12', 'new13', 'new14', 'new15', 'new16', 'new17', 'new18', 'new1', 'new2', 'new3', 'new4', 'new5', 'new6', 'new7', 'new8', 'new9', 'new10', 'new11', 'crcd1', 'crcd2', 'crcd3', 'crcd4', 'crcd5', 'interval_date1', 'cus_asset_bal1', 'cus_asset_bal2', 'cus_marr_stat1'\n",
    "        ]\n",
    "cago_feature=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]\n",
    "cago_feature=[]\n",
    "feature_train=feature+['target']\n",
    "feature_test=feature\n",
    "dataset_train=dataset_train[feature_train]\n",
    "dataset_test=dataset_test[feature_test]\n",
    "seed=None\n",
    "dataset_train_x,dataset_train_y=get_sample(dataset_train[feature_train],target_0=1,target_1=1,seed=seed)\n",
    "X_train,X_test,Y_train,Y_test=train_test_split(dataset_train_x,dataset_train_y,test_size=0.2,random_state=seed)\n",
    "\n",
    "model = catboost.CatBoostClassifier(iterations=17000,\n",
    "                              depth = 6,\n",
    "                               learning_rate = 0.03,\n",
    "                               custom_loss='AUC',\n",
    "                               eval_metric='AUC',\n",
    "                               bagging_temperature=0.83,\n",
    "                               od_type='Iter',\n",
    "                               rsm = 0.78,\n",
    "                               od_wait=150,\n",
    "                               l2_leaf_reg = 5,\n",
    "                               thread_count = 20,\n",
    "                               random_seed = 967\n",
    "                              )\n",
    "model.fit(X_train, Y_train, eval_set=(X_test, Y_test),use_best_model=True)\n",
    "pre= model.predict_proba(X_test)[:,1]#.reshape((X_test.shape[0],1))\n",
    "\n",
    "print (roc_auc_score(Y_test, pre))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
